"""
Django settings for Django Project

Generated by 'django-admin startproject' using Django 5.1

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For a full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdirectory
BASE_DIR = Path(__file__).resolve.parent.parent

